--Creating Tables
CREATE TABLE PRODUCT(
    P_ID INTEGER PRIMARY KEY,
    P_NAME VARCHAR(15),
    CAT_ID INTEGER,
    UNIT_PRICE FLOAT(5)
);

CREATE TABLE CATEGORY(
    CAT_ID INTEGER PRIMARY KEY,
    CAT_NAME VARCHAR(15)
);

CREATE TABLE CUSTOMER(
    C_ID INTEGER PRIMARY KEY,
    C_NAME VARCHAR(20),
    C_DOB DATE,
    C_GENDER CHAR(1),
    C_MOBILE VARCHAR(10),
    LOCO_ID INTEGER,
    CONSTRAINT CHECK_CUSTOMER_GENDER CHECK(C_GENDER IN ('M','F','O'))
);

CREATE TABLE SALES_EXE(
    SE_ID INTEGER,
    SE_NAME VARCHAR(20),
    SE_DOB DATE,
    SE_GENDER CHAR(1),
    SE_MOBILE VARCHAR(10),
    CONSTRAINT CHECK_SE_GENDER CHECK(SE_GENDER IN('M','F','O')),
    PRIMARY KEY(SE_ID)
);

CREATE TABLE LOCATION(
    LOCO_ID INTEGER PRIMARY KEY,
    LOCO_NAME VARCHAR(15)
);

CREATE TABLE LOCODATA(
    LOCO_ID INTEGER,
    SE_ID INTEGER,
    PRIMARY KEY(LOCO_ID,SE_ID)
);

CREATE TABLE SALES(
    C_ID INTEGER,
    P_ID INTEGER,
    SE_ID INTEGER,
    DOP DATE,
    NOU INT,
    PRIMARY KEY(C_ID, P_ID, DOP)
);

-- Updating Foreign keys to the tables
ALTER TABLE PRODUCT ADD FOREIGN KEY (CAT_ID) REFERENCES CATEGORY(CAT_ID);
ALTER TABLE CUSTOMER ADD FOREIGN KEY (LOCO_ID) REFERENCES LOCATION(LOCO_ID);
ALTER TABLE LOCODATA ADD FOREIGN KEY (SE_ID) REFERENCES SALES_EXE(SE_ID);
ALTER TABLE SALES ADD FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID);
ALTER TABLE SALES ADD FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID);
ALTER TABLE SALES ADD FOREIGN KEY (SE_ID) REFERENCES SALES_EXE(SE_ID);